---
- hosts: test
  gather_facts: no
  become: yes

  roles:
    - common
    - mail
    - rainloop
    - gogs
    - web
    - openvpn
    - ikev2
    - mtproto
    - speedtest

  tasks:
    - name:
      import_role:
        name: common
        tasks_from: reboot.yml
