---
- name:
  import_tasks: push.yml
  tags:
    - mtproto-push

- name:
  import_tasks: pull.yml
  tags:
    - mtproto-pull

- name:
  import_tasks: app_present.yml
  tags:
    - mtproto-up

- name:
  import_tasks: app_absent.yml
  tags:
    - mtproto-down
