---
- name:
  import_tasks: push.yml
  tags:
    - rainloop-push

- name:
  import_tasks: pull.yml
  tags:
    - rainloop-pull

- name:
  import_tasks: app_present.yml
  tags:
    - rainloop-up

- name:
  import_tasks: app_absent.yml
  tags:
    - rainloop-down
