---
- name:
  import_tasks: push.yml
  tags:
    - speedtest-push

- name:
  import_tasks: pull.yml
  tags:
    - speedtest-pull

- name:
  import_tasks: app_present.yml
  tags:
    - speedtest-up

- name:
  import_tasks: app_absent.yml
  tags:
    - speedtest-down
