---
- name: install duplicity
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - duplicity
      - python-pip

- name: install b2 module
  pip:
    name: b2
    executable: pip
