---
- name:
  import_tasks: push.yml
  tags:
    - web-push

- name:
  import_tasks: pull.yml
  tags:
    - web-pull

- name:
  import_tasks: app_present.yml
  tags:
    - web-up

- name:
  import_tasks: app_absent.yml
  tags:
    - web-down
