---
- name: reboot the server
  shell: sleep 5 && shutdown -r now "Ansible reboot"
  async: 1
  poll: 0

- name: wait for the reboot to complete
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
