---
- name: install software
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
      - make
      - python3-pip

- name: install docker module
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - docker
      - docker-compose
