---
- name: install software
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - make
    - python3-pip

- name: install docker module
  pip:
    name: "{{ item }}"
  with_items:
    - docker
    - docker-compose
