---
- name:
  import_tasks: push.yml
  tags:
    - openvpn-push

- name:
  import_tasks: pull.yml
  tags:
    - openvpn-pull

- name:
  import_tasks: app_present.yml
  tags:
    - openvpn-up

- name:
  import_tasks: app_absent.yml
  tags:
    - openvpn-down
